# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kluck Engineering"
email: "steve at kluck.engineering"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kluck.engineering"

# Social settings
whoami: "Steve Kluck"
github_url: "https://github.com/skluck"

location:
    city: "Detroit, Michigan"
    country: "USA"

job:
    title: "Principal Software Engineer"
    company: "Quicken Loans"
    responsibilities:
      - "Lead developer on engineering team within QL Enterprise Services."
      - "Design, implement, and maintain PHP applications."
      - "Maintain core shared PHP libraries for use throughout company."
      - "Develop release pipeline platform."
      - "Mentor other engineers, define best practices."


# Build settings
markdown: "kramdown"

logo: ""
